import type {
  AnalysisResult,
  ImageAnalysisInput,
  ImageAnalyzer,
} from "./types";

export class OfflinePestDemoAnalyzer
  implements ImageAnalyzer
{
  readonly source = "local" as const;

  async analyzeImage({
    image,
  }: ImageAnalysisInput): Promise<AnalysisResult> {
    void image;

    return {
      category: "Pest",
      identifiedName: "Fall Armyworm",
      commonName: "Fall Armyworm",
      scientificName: "Spodoptera frugiperda",
      confidence: 94,
      description:
        "This result was generated by the AgroBioGuard local pest demonstration engine. The uploaded image is used as the demo interaction input.",
      riskLevel: "high",
      riskDescription:
        "Fall Armyworm can damage agricultural crops and requires monitoring.",
      recommendation:
        "Inspect nearby crops for feeding damage and confirm the identification before applying pest-control measures.",
      locationContext:
        "The local demonstration can be combined with device location context.",
      analysisSource: "local",
      provider: {
        id: "agrobioguard-offline-pest-demo",
        model: "Local Pest Demo",
      },
      status: "complete",
    };
  }
}